default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: apiexample
  password: <%= ENV['APIEXAMPLE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: apiexample_development

test:
  <<: *default
  database: apiexample_test

production:
  <<: *default
  database: apiexample_production
  username: apiexample
